# Generated by Django 4.2.5 on 2023-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=1000)),
                ('project_title', models.CharField(max_length=1000)),
                ('project_domain', models.CharField(max_length=1000)),
                ('project_content', models.DateTimeField()),
                ('university_name', models.CharField(max_length=1000)),
                ('student_photo', models.ImageField(upload_to='uploads/')),
                ('project_cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
